### ISSUE TITLE
Synda selection file conversion fails if there is no ".txt" extension

### ISSUE THREAD

**Issue by meteorologist15** [ESGF/esgf-download#34]
Virtually all of my Synda selection files do not have a literal ".txt" extension attached to them (despite them still being text files), and thus, while attempting conversion using esgpull convert ..., esgpull silently failed and did not create a query. When I attached the ".txt" extension to the Synda selection file, esgpull successfully converted my file. I presume the intended functionality is to perform the conversion regardless if a '.txt' extension is attached to the filename.

**Comment by svenrdz** [comment]
Hi @meteorologist15, thanks for reaching out !

This extension filter was introduced as a heuristic to convert only valid files, since all our selection files had txt extension, and so did all the examples I found in the original `synda` repository.

I've just pushed changes that should enable the previous behaviour with a better heuristic based on the output rather than the input of the convert process. I'll get this merged with a new conda version quickly.
